--
-- Upgrade script for name snafoo fix
-- Fixes the scraping naming snafoo by updating rows in states and states_series
-- Created: Sun May  3 15:41:50 2015
--

BEGIN;

-- UPDATE series.title according to the re-mappings
UPDATE series SET title='Mississippi, not seasonally adjusted - unemployment' WHERE id=3;
UPDATE series SET title='Mississippi, not seasonally adjusted - unemployment rate' WHERE id=4;
UPDATE series SET title='Mississippi, seasonally adjusted - employment' WHERE id=5;
UPDATE series SET title='Mississippi, seasonally adjusted - unemployment' WHERE id=6;
UPDATE series SET title='Mississippi, seasonally adjusted - labor force' WHERE id=7;
UPDATE series SET title='Mississippi, seasonally adjusted - unemployment rate' WHERE id=8;
UPDATE series SET title='Oklahoma, not seasonally adjusted - unemployment rate' WHERE id=9;
UPDATE series SET title='Oklahoma, not seasonally adjusted - employment' WHERE id=10;
UPDATE series SET title='Oklahoma, not seasonally adjusted - unemployment' WHERE id=11;
UPDATE series SET title='Oklahoma, not seasonally adjusted - labor force' WHERE id=12;
UPDATE series SET title='Oklahoma, seasonally adjusted - unemployment rate' WHERE id=13;
UPDATE series SET title='Oklahoma, seasonally adjusted - labor force' WHERE id=14;
UPDATE series SET title='Oklahoma, seasonally adjusted - employment' WHERE id=15;
UPDATE series SET title='Oklahoma, seasonally adjusted - unemployment' WHERE id=16;
UPDATE series SET title='Wyoming, not seasonally adjusted - unemployment rate' WHERE id=17;
UPDATE series SET title='Wyoming, not seasonally adjusted - labor force' WHERE id=18;
UPDATE series SET title='Wyoming, not seasonally adjusted - unemployment' WHERE id=19;
UPDATE series SET title='Wyoming, not seasonally adjusted - employment' WHERE id=20;
UPDATE series SET title='Wyoming, seasonally adjusted - unemployment rate' WHERE id=21;
UPDATE series SET title='Wyoming, seasonally adjusted - unemployment' WHERE id=22;
UPDATE series SET title='Wyoming, seasonally adjusted - employment' WHERE id=23;
UPDATE series SET title='Wyoming, seasonally adjusted - labor force' WHERE id=24;
UPDATE series SET title='Minnesota, seasonally adjusted - unemployment rate' WHERE id=25;
UPDATE series SET title='Minnesota, seasonally adjusted - unemployment' WHERE id=26;
UPDATE series SET title='Minnesota, seasonally adjusted - employment' WHERE id=27;
UPDATE series SET title='Minnesota, seasonally adjusted - labor force' WHERE id=28;
UPDATE series SET title='Minnesota, not seasonally adjusted - labor force' WHERE id=29;
UPDATE series SET title='Minnesota, not seasonally adjusted - unemployment' WHERE id=30;
UPDATE series SET title='Minnesota, not seasonally adjusted - employment' WHERE id=31;
UPDATE series SET title='Minnesota, not seasonally adjusted - unemployment rate' WHERE id=32;
UPDATE series SET title='Illinois, not seasonally adjusted - unemployment rate' WHERE id=33;
UPDATE series SET title='Illinois, not seasonally adjusted - employment' WHERE id=34;
UPDATE series SET title='Illinois, not seasonally adjusted - unemployment' WHERE id=35;
UPDATE series SET title='Illinois, not seasonally adjusted - labor force' WHERE id=36;
UPDATE series SET title='Illinois, seasonally adjusted - labor force' WHERE id=37;
UPDATE series SET title='Illinois, seasonally adjusted - employment' WHERE id=38;
UPDATE series SET title='Illinois, seasonally adjusted - unemployment' WHERE id=39;
UPDATE series SET title='Illinois, seasonally adjusted - unemployment rate' WHERE id=40;
UPDATE series SET title='Arkansas, seasonally adjusted - unemployment rate' WHERE id=41;
UPDATE series SET title='Arkansas, seasonally adjusted - unemployment' WHERE id=42;
UPDATE series SET title='Arkansas, seasonally adjusted - employment' WHERE id=43;
UPDATE series SET title='Arkansas, seasonally adjusted - labor force' WHERE id=44;
UPDATE series SET title='Arkansas, not seasonally adjusted - labor force' WHERE id=45;
UPDATE series SET title='Arkansas, not seasonally adjusted - unemployment' WHERE id=46;
UPDATE series SET title='Arkansas, not seasonally adjusted - employment' WHERE id=47;
UPDATE series SET title='Arkansas, not seasonally adjusted - unemployment rate' WHERE id=48;
UPDATE series SET title='New Mexico, not seasonally adjusted - employment' WHERE id=49;
UPDATE series SET title='New Mexico, not seasonally adjusted - unemployment' WHERE id=50;
UPDATE series SET title='New Mexico, not seasonally adjusted - labor force' WHERE id=51;
UPDATE series SET title='New Mexico, not seasonally adjusted - unemployment rate' WHERE id=52;
UPDATE series SET title='New Mexico, seasonally adjusted - unemployment rate' WHERE id=53;
UPDATE series SET title='New Mexico, seasonally adjusted - labor force' WHERE id=54;
UPDATE series SET title='New Mexico, seasonally adjusted - employment' WHERE id=55;
UPDATE series SET title='New Mexico, seasonally adjusted - unemployment' WHERE id=56;
UPDATE series SET title='Ohio, seasonally adjusted - labor force' WHERE id=57;
UPDATE series SET title='Ohio, seasonally adjusted - employment' WHERE id=58;
UPDATE series SET title='Ohio, seasonally adjusted - unemployment' WHERE id=59;
UPDATE series SET title='Ohio, seasonally adjusted - unemployment rate' WHERE id=60;
UPDATE series SET title='Ohio, not seasonally adjusted - unemployment rate' WHERE id=61;
UPDATE series SET title='Ohio, not seasonally adjusted - employment' WHERE id=62;
UPDATE series SET title='Ohio, not seasonally adjusted - unemployment' WHERE id=63;
UPDATE series SET title='Ohio, not seasonally adjusted - labor force' WHERE id=64;
UPDATE series SET title='Indiana, seasonally adjusted - labor force' WHERE id=65;
UPDATE series SET title='Indiana, seasonally adjusted - unemployment' WHERE id=66;
UPDATE series SET title='Indiana, seasonally adjusted - employment' WHERE id=67;
UPDATE series SET title='Indiana, seasonally adjusted - unemployment rate' WHERE id=68;
UPDATE series SET title='Indiana, not seasonally adjusted - unemployment' WHERE id=69;
UPDATE series SET title='Indiana, not seasonally adjusted - employment' WHERE id=70;
UPDATE series SET title='Indiana, not seasonally adjusted - labor force' WHERE id=71;
UPDATE series SET title='Indiana, not seasonally adjusted - unemployment rate' WHERE id=72;
UPDATE series SET title='Maryland, seasonally adjusted - unemployment rate' WHERE id=73;
UPDATE series SET title='Maryland, seasonally adjusted - employment' WHERE id=74;
UPDATE series SET title='Mississippi, not seasonally adjusted - employment' WHERE id=2;
UPDATE series SET title='Maryland, seasonally adjusted - unemployment' WHERE id=75;
UPDATE series SET title='Maryland, seasonally adjusted - labor force' WHERE id=76;
UPDATE series SET title='Maryland, not seasonally adjusted - unemployment rate' WHERE id=77;
UPDATE series SET title='Maryland, not seasonally adjusted - labor force' WHERE id=78;
UPDATE series SET title='Maryland, not seasonally adjusted - employment' WHERE id=79;
UPDATE series SET title='Maryland, not seasonally adjusted - unemployment' WHERE id=80;
UPDATE series SET title='Louisiana, seasonally adjusted - labor force' WHERE id=81;
UPDATE series SET title='Louisiana, seasonally adjusted - employment' WHERE id=82;
UPDATE series SET title='Louisiana, seasonally adjusted - unemployment' WHERE id=83;
UPDATE series SET title='Louisiana, seasonally adjusted - unemployment rate' WHERE id=84;
UPDATE series SET title='Louisiana, not seasonally adjusted - employment' WHERE id=85;
UPDATE series SET title='Louisiana, not seasonally adjusted - unemployment' WHERE id=86;
UPDATE series SET title='Louisiana, not seasonally adjusted - labor force' WHERE id=87;
UPDATE series SET title='Louisiana, not seasonally adjusted - unemployment rate' WHERE id=88;
UPDATE series SET title='Idaho, seasonally adjusted - unemployment' WHERE id=89;
UPDATE series SET title='Idaho, seasonally adjusted - employment' WHERE id=90;
UPDATE series SET title='Idaho, seasonally adjusted - labor force' WHERE id=91;
UPDATE series SET title='Idaho, seasonally adjusted - unemployment rate' WHERE id=92;
UPDATE series SET title='Idaho, not seasonally adjusted - labor force' WHERE id=93;
UPDATE series SET title='Idaho, not seasonally adjusted - unemployment' WHERE id=94;
UPDATE series SET title='Idaho, not seasonally adjusted - employment' WHERE id=95;
UPDATE series SET title='Idaho, not seasonally adjusted - unemployment rate' WHERE id=96;
UPDATE series SET title='Arizona, not seasonally adjusted - unemployment rate' WHERE id=97;
UPDATE series SET title='Arizona, not seasonally adjusted - employment' WHERE id=98;
UPDATE series SET title='Arizona, not seasonally adjusted - unemployment' WHERE id=99;
UPDATE series SET title='Arizona, not seasonally adjusted - labor force' WHERE id=100;
UPDATE series SET title='Arizona, seasonally adjusted - unemployment rate' WHERE id=101;
UPDATE series SET title='Arizona, seasonally adjusted - labor force' WHERE id=102;
UPDATE series SET title='Arizona, seasonally adjusted - employment' WHERE id=103;
UPDATE series SET title='Arizona, seasonally adjusted - unemployment' WHERE id=104;
UPDATE series SET title='Iowa, not seasonally adjusted - labor force' WHERE id=105;
UPDATE series SET title='Iowa, not seasonally adjusted - employment' WHERE id=106;
UPDATE series SET title='Iowa, not seasonally adjusted - unemployment' WHERE id=107;
UPDATE series SET title='Iowa, not seasonally adjusted - unemployment rate' WHERE id=108;
UPDATE series SET title='Iowa, seasonally adjusted - unemployment rate' WHERE id=109;
UPDATE series SET title='Iowa, seasonally adjusted - employment' WHERE id=110;
UPDATE series SET title='Iowa, seasonally adjusted - unemployment' WHERE id=111;
UPDATE series SET title='Iowa, seasonally adjusted - labor force' WHERE id=112;
UPDATE series SET title='New York, not seasonally adjusted - unemployment' WHERE id=113;
UPDATE series SET title='New York, not seasonally adjusted - employment' WHERE id=114;
UPDATE series SET title='New York, not seasonally adjusted - labor force' WHERE id=115;
UPDATE series SET title='New York, not seasonally adjusted - unemployment rate' WHERE id=116;
UPDATE series SET title='New York, seasonally adjusted - labor force' WHERE id=117;
UPDATE series SET title='New York, seasonally adjusted - unemployment' WHERE id=118;
UPDATE series SET title='New York, seasonally adjusted - employment' WHERE id=119;
UPDATE series SET title='New York, seasonally adjusted - unemployment rate' WHERE id=120;
UPDATE series SET title='Michigan, not seasonally adjusted - unemployment rate' WHERE id=121;
UPDATE series SET title='Michigan, not seasonally adjusted - employment' WHERE id=122;
UPDATE series SET title='Michigan, not seasonally adjusted - unemployment' WHERE id=123;
UPDATE series SET title='Michigan, not seasonally adjusted - labor force' WHERE id=124;
UPDATE series SET title='Michigan, seasonally adjusted - unemployment rate' WHERE id=125;
UPDATE series SET title='Michigan, seasonally adjusted - labor force' WHERE id=126;
UPDATE series SET title='Michigan, seasonally adjusted - employment' WHERE id=127;
UPDATE series SET title='Michigan, seasonally adjusted - unemployment' WHERE id=128;
UPDATE series SET title='Kansas, not seasonally adjusted - labor force' WHERE id=129;
UPDATE series SET title='Kansas, not seasonally adjusted - employment' WHERE id=130;
UPDATE series SET title='Kansas, not seasonally adjusted - unemployment' WHERE id=131;
UPDATE series SET title='Kansas, not seasonally adjusted - unemployment rate' WHERE id=132;
UPDATE series SET title='Kansas, seasonally adjusted - employment' WHERE id=133;
UPDATE series SET title='Kansas, seasonally adjusted - unemployment' WHERE id=134;
UPDATE series SET title='Kansas, seasonally adjusted - labor force' WHERE id=135;
UPDATE series SET title='Kansas, seasonally adjusted - unemployment rate' WHERE id=136;
UPDATE series SET title='Utah, not seasonally adjusted - labor force' WHERE id=137;
UPDATE series SET title='Utah, not seasonally adjusted - unemployment' WHERE id=138;
UPDATE series SET title='Utah, not seasonally adjusted - employment' WHERE id=139;
UPDATE series SET title='Utah, not seasonally adjusted - unemployment rate' WHERE id=140;
UPDATE series SET title='Utah, seasonally adjusted - unemployment rate' WHERE id=141;
UPDATE series SET title='Utah, seasonally adjusted - unemployment' WHERE id=142;
UPDATE series SET title='Utah, seasonally adjusted - employment' WHERE id=143;
UPDATE series SET title='Utah, seasonally adjusted - labor force' WHERE id=144;
UPDATE series SET title='Virginia, seasonally adjusted - employment' WHERE id=145;
UPDATE series SET title='Virginia, seasonally adjusted - unemployment' WHERE id=146;
UPDATE series SET title='Virginia, seasonally adjusted - labor force' WHERE id=147;
UPDATE series SET title='Virginia, seasonally adjusted - unemployment rate' WHERE id=148;
UPDATE series SET title='Virginia, not seasonally adjusted - unemployment rate' WHERE id=149;
UPDATE series SET title='Virginia, not seasonally adjusted - labor force' WHERE id=150;
UPDATE series SET title='Virginia, not seasonally adjusted - employment' WHERE id=151;
UPDATE series SET title='Virginia, not seasonally adjusted - unemployment' WHERE id=152;
UPDATE series SET title='Oregon, not seasonally adjusted - labor force' WHERE id=153;
UPDATE series SET title='Oregon, not seasonally adjusted - unemployment' WHERE id=154;
UPDATE series SET title='Oregon, not seasonally adjusted - employment' WHERE id=155;
UPDATE series SET title='Oregon, not seasonally adjusted - unemployment rate' WHERE id=156;
UPDATE series SET title='Oregon, seasonally adjusted - unemployment rate' WHERE id=157;
UPDATE series SET title='Oregon, seasonally adjusted - unemployment' WHERE id=158;
UPDATE series SET title='Oregon, seasonally adjusted - employment' WHERE id=159;
UPDATE series SET title='Oregon, seasonally adjusted - labor force' WHERE id=160;
UPDATE series SET title='Connecticut, seasonally adjusted - unemployment' WHERE id=161;
UPDATE series SET title='Connecticut, seasonally adjusted - employment' WHERE id=162;
UPDATE series SET title='Connecticut, seasonally adjusted - labor force' WHERE id=163;
UPDATE series SET title='Connecticut, seasonally adjusted - unemployment rate' WHERE id=164;
UPDATE series SET title='Connecticut, not seasonally adjusted - unemployment rate' WHERE id=165;
UPDATE series SET title='Connecticut, not seasonally adjusted - labor force' WHERE id=166;
UPDATE series SET title='Connecticut, not seasonally adjusted - unemployment' WHERE id=167;
UPDATE series SET title='Connecticut, not seasonally adjusted - employment' WHERE id=168;
UPDATE series SET title='Montana, seasonally adjusted - unemployment' WHERE id=169;
UPDATE series SET title='Montana, seasonally adjusted - employment' WHERE id=170;
UPDATE series SET title='Montana, seasonally adjusted - labor force' WHERE id=171;
UPDATE series SET title='Montana, seasonally adjusted - unemployment rate' WHERE id=172;
UPDATE series SET title='Montana, not seasonally adjusted - labor force' WHERE id=173;
UPDATE series SET title='Montana, not seasonally adjusted - unemployment' WHERE id=174;
UPDATE series SET title='Montana, not seasonally adjusted - employment' WHERE id=175;
UPDATE series SET title='Montana, not seasonally adjusted - unemployment rate' WHERE id=176;
UPDATE series SET title='California, not seasonally adjusted - unemployment rate' WHERE id=177;
UPDATE series SET title='California, not seasonally adjusted - labor force' WHERE id=178;
UPDATE series SET title='California, not seasonally adjusted - employment' WHERE id=179;
UPDATE series SET title='California, not seasonally adjusted - unemployment' WHERE id=180;
UPDATE series SET title='California, seasonally adjusted - unemployment rate' WHERE id=181;
UPDATE series SET title='California, seasonally adjusted - employment' WHERE id=182;
UPDATE series SET title='California, seasonally adjusted - unemployment' WHERE id=183;
UPDATE series SET title='California, seasonally adjusted - labor force' WHERE id=184;
UPDATE series SET title='Massachusetts, not seasonally adjusted - unemployment rate' WHERE id=185;
UPDATE series SET title='Massachusetts, not seasonally adjusted - unemployment' WHERE id=186;
UPDATE series SET title='Massachusetts, not seasonally adjusted - employment' WHERE id=187;
UPDATE series SET title='Massachusetts, not seasonally adjusted - labor force' WHERE id=188;
UPDATE series SET title='Massachusetts, seasonally adjusted - labor force' WHERE id=189;
UPDATE series SET title='Massachusetts, seasonally adjusted - unemployment' WHERE id=190;
UPDATE series SET title='Massachusetts, seasonally adjusted - employment' WHERE id=191;
UPDATE series SET title='Massachusetts, seasonally adjusted - unemployment rate' WHERE id=192;
UPDATE series SET title='Puerto Rico, seasonally adjusted - labor force' WHERE id=193;
UPDATE series SET title='Puerto Rico, seasonally adjusted - unemployment' WHERE id=194;
UPDATE series SET title='Puerto Rico, seasonally adjusted - employment' WHERE id=195;
UPDATE series SET title='Puerto Rico, seasonally adjusted - unemployment rate' WHERE id=196;
UPDATE series SET title='Puerto Rico, not seasonally adjusted - unemployment' WHERE id=197;
UPDATE series SET title='Puerto Rico, not seasonally adjusted - employment' WHERE id=198;
UPDATE series SET title='Puerto Rico, not seasonally adjusted - labor force' WHERE id=199;
UPDATE series SET title='Puerto Rico, not seasonally adjusted - unemployment rate' WHERE id=200;
UPDATE series SET title='South Carolina, not seasonally adjusted - unemployment rate' WHERE id=201;
UPDATE series SET title='South Carolina, not seasonally adjusted - labor force' WHERE id=202;
UPDATE series SET title='South Carolina, not seasonally adjusted - unemployment' WHERE id=203;
UPDATE series SET title='South Carolina, not seasonally adjusted - employment' WHERE id=204;
UPDATE series SET title='South Carolina, seasonally adjusted - unemployment' WHERE id=205;
UPDATE series SET title='South Carolina, seasonally adjusted - employment' WHERE id=206;
UPDATE series SET title='South Carolina, seasonally adjusted - labor force' WHERE id=207;
UPDATE series SET title='South Carolina, seasonally adjusted - unemployment rate' WHERE id=208;
UPDATE series SET title='New Hampshire, not seasonally adjusted - unemployment rate' WHERE id=209;
UPDATE series SET title='New Hampshire, not seasonally adjusted - labor force' WHERE id=210;
UPDATE series SET title='New Hampshire, not seasonally adjusted - employment' WHERE id=211;
UPDATE series SET title='New Hampshire, not seasonally adjusted - unemployment' WHERE id=212;
UPDATE series SET title='New Hampshire, seasonally adjusted - employment' WHERE id=213;
UPDATE series SET title='New Hampshire, seasonally adjusted - unemployment' WHERE id=214;
UPDATE series SET title='New Hampshire, seasonally adjusted - labor force' WHERE id=215;
UPDATE series SET title='New Hampshire, seasonally adjusted - unemployment rate' WHERE id=216;
UPDATE series SET title='Vermont, not seasonally adjusted - unemployment rate' WHERE id=217;
UPDATE series SET title='Vermont, not seasonally adjusted - unemployment' WHERE id=218;
UPDATE series SET title='Vermont, not seasonally adjusted - employment' WHERE id=219;
UPDATE series SET title='Vermont, not seasonally adjusted - labor force' WHERE id=220;
UPDATE series SET title='Vermont, seasonally adjusted - unemployment rate' WHERE id=221;
UPDATE series SET title='Vermont, seasonally adjusted - labor force' WHERE id=222;
UPDATE series SET title='Vermont, seasonally adjusted - unemployment' WHERE id=223;
UPDATE series SET title='Vermont, seasonally adjusted - employment' WHERE id=224;
UPDATE series SET title='Delaware, not seasonally adjusted - unemployment' WHERE id=225;
UPDATE series SET title='Delaware, not seasonally adjusted - employment' WHERE id=226;
UPDATE series SET title='Delaware, not seasonally adjusted - labor force' WHERE id=227;
UPDATE series SET title='Delaware, not seasonally adjusted - unemployment rate' WHERE id=228;
UPDATE series SET title='Delaware, seasonally adjusted - labor force' WHERE id=229;
UPDATE series SET title='Delaware, seasonally adjusted - unemployment' WHERE id=230;
UPDATE series SET title='Delaware, seasonally adjusted - employment' WHERE id=231;
UPDATE series SET title='Delaware, seasonally adjusted - unemployment rate' WHERE id=232;
UPDATE series SET title='North Dakota, not seasonally adjusted - labor force' WHERE id=233;
UPDATE series SET title='North Dakota, not seasonally adjusted - unemployment' WHERE id=234;
UPDATE series SET title='North Dakota, not seasonally adjusted - employment' WHERE id=235;
UPDATE series SET title='North Dakota, not seasonally adjusted - unemployment rate' WHERE id=236;
UPDATE series SET title='North Dakota, seasonally adjusted - unemployment' WHERE id=237;
UPDATE series SET title='North Dakota, seasonally adjusted - employment' WHERE id=238;
UPDATE series SET title='North Dakota, seasonally adjusted - labor force' WHERE id=239;
UPDATE series SET title='North Dakota, seasonally adjusted - unemployment rate' WHERE id=240;
UPDATE series SET title='Pennsylvania, seasonally adjusted - unemployment rate' WHERE id=241;
UPDATE series SET title='Pennsylvania, seasonally adjusted - employment' WHERE id=242;
UPDATE series SET title='Pennsylvania, seasonally adjusted - unemployment' WHERE id=243;
UPDATE series SET title='Pennsylvania, seasonally adjusted - labor force' WHERE id=244;
UPDATE series SET title='Pennsylvania, not seasonally adjusted - unemployment rate' WHERE id=245;
UPDATE series SET title='Pennsylvania, not seasonally adjusted - labor force' WHERE id=246;
UPDATE series SET title='Pennsylvania, not seasonally adjusted - employment' WHERE id=247;
UPDATE series SET title='Pennsylvania, not seasonally adjusted - unemployment' WHERE id=248;
UPDATE series SET title='West Virginia, not seasonally adjusted - unemployment' WHERE id=249;
UPDATE series SET title='West Virginia, not seasonally adjusted - employment' WHERE id=250;
UPDATE series SET title='West Virginia, not seasonally adjusted - labor force' WHERE id=251;
UPDATE series SET title='West Virginia, seasonally adjusted - employment' WHERE id=252;
UPDATE series SET title='West Virginia, seasonally adjusted - unemployment rate' WHERE id=253;
UPDATE series SET title='West Virginia, not seasonally adjusted - unemployment rate' WHERE id=254;
UPDATE series SET title='West Virginia, seasonally adjusted - unemployment' WHERE id=255;
UPDATE series SET title='West Virginia, seasonally adjusted - labor force' WHERE id=256;
UPDATE series SET title='Florida, not seasonally adjusted - unemployment rate' WHERE id=257;
UPDATE series SET title='Florida, seasonally adjusted - unemployment rate' WHERE id=258;
UPDATE series SET title='Florida, not seasonally adjusted - labor force' WHERE id=259;
UPDATE series SET title='Florida, seasonally adjusted - employment' WHERE id=260;
UPDATE series SET title='Florida, not seasonally adjusted - unemployment' WHERE id=261;
UPDATE series SET title='Florida, not seasonally adjusted - employment' WHERE id=262;
UPDATE series SET title='Florida, seasonally adjusted - labor force' WHERE id=263;
UPDATE series SET title='Florida, seasonally adjusted - unemployment' WHERE id=264;
UPDATE series SET title='Alaska, seasonally adjusted - employment' WHERE id=265;
UPDATE series SET title='Alaska, seasonally adjusted - unemployment' WHERE id=266;
UPDATE series SET title='Alaska, seasonally adjusted - labor force' WHERE id=267;
UPDATE series SET title='Alaska, seasonally adjusted - unemployment rate' WHERE id=268;
UPDATE series SET title='Alaska, not seasonally adjusted - labor force' WHERE id=269;
UPDATE series SET title='Alaska, not seasonally adjusted - employment' WHERE id=270;
UPDATE series SET title='Alaska, not seasonally adjusted - unemployment' WHERE id=271;
UPDATE series SET title='Alaska, not seasonally adjusted - unemployment rate' WHERE id=272;
UPDATE series SET title='Kentucky, not seasonally adjusted - unemployment' WHERE id=273;
UPDATE series SET title='Kentucky, not seasonally adjusted - employment' WHERE id=274;
UPDATE series SET title='Kentucky, not seasonally adjusted - labor force' WHERE id=275;
UPDATE series SET title='Kentucky, seasonally adjusted - labor force' WHERE id=276;
UPDATE series SET title='Kentucky, seasonally adjusted - unemployment' WHERE id=277;
UPDATE series SET title='Kentucky, seasonally adjusted - unemployment rate' WHERE id=278;
UPDATE series SET title='Kentucky, seasonally adjusted - employment' WHERE id=279;
UPDATE series SET title='Kentucky, not seasonally adjusted - unemployment rate' WHERE id=280;
UPDATE series SET title='Hawaii, not seasonally adjusted - unemployment rate' WHERE id=281;
UPDATE series SET title='Hawaii, not seasonally adjusted - labor force' WHERE id=282;
UPDATE series SET title='Hawaii, not seasonally adjusted - employment' WHERE id=283;
UPDATE series SET title='Hawaii, not seasonally adjusted - unemployment' WHERE id=284;
UPDATE series SET title='Hawaii, seasonally adjusted - employment' WHERE id=285;
UPDATE series SET title='Hawaii, seasonally adjusted - unemployment' WHERE id=286;
UPDATE series SET title='Hawaii, seasonally adjusted - labor force' WHERE id=287;
UPDATE series SET title='Hawaii, seasonally adjusted - unemployment rate' WHERE id=288;
UPDATE series SET title='Nebraska, not seasonally adjusted - unemployment rate' WHERE id=289;
UPDATE series SET title='Nebraska, not seasonally adjusted - employment' WHERE id=290;
UPDATE series SET title='Nebraska, not seasonally adjusted - unemployment' WHERE id=291;
UPDATE series SET title='Nebraska, not seasonally adjusted - labor force' WHERE id=292;
UPDATE series SET title='Nebraska, seasonally adjusted - labor force' WHERE id=293;
UPDATE series SET title='Nebraska, seasonally adjusted - employment' WHERE id=294;
UPDATE series SET title='Nebraska, seasonally adjusted - unemployment' WHERE id=295;
UPDATE series SET title='Nebraska, seasonally adjusted - unemployment rate' WHERE id=296;
UPDATE series SET title='Missouri, not seasonally adjusted - employment' WHERE id=297;
UPDATE series SET title='Missouri, not seasonally adjusted - unemployment' WHERE id=298;
UPDATE series SET title='Missouri, seasonally adjusted - unemployment rate' WHERE id=299;
UPDATE series SET title='Missouri, not seasonally adjusted - labor force' WHERE id=300;
UPDATE series SET title='Missouri, not seasonally adjusted - unemployment rate' WHERE id=301;
UPDATE series SET title='Missouri, seasonally adjusted - labor force' WHERE id=302;
UPDATE series SET title='Missouri, seasonally adjusted - unemployment' WHERE id=303;
UPDATE series SET title='Missouri, seasonally adjusted - employment' WHERE id=304;
UPDATE series SET title='Wisconsin, not seasonally adjusted - employment' WHERE id=305;
UPDATE series SET title='Wisconsin, not seasonally adjusted - labor force' WHERE id=306;
UPDATE series SET title='Wisconsin, seasonally adjusted - unemployment rate' WHERE id=307;
UPDATE series SET title='Wisconsin, not seasonally adjusted - unemployment' WHERE id=308;
UPDATE series SET title='Wisconsin, not seasonally adjusted - unemployment rate' WHERE id=309;
UPDATE series SET title='Wisconsin, seasonally adjusted - unemployment' WHERE id=310;
UPDATE series SET title='Wisconsin, seasonally adjusted - labor force' WHERE id=311;
UPDATE series SET title='Wisconsin, seasonally adjusted - employment' WHERE id=312;
UPDATE series SET title='Alabama, not seasonally adjusted - unemployment rate' WHERE id=313;
UPDATE series SET title='Alabama, not seasonally adjusted - labor force' WHERE id=314;
UPDATE series SET title='Alabama, not seasonally adjusted - unemployment' WHERE id=315;
UPDATE series SET title='Alabama, not seasonally adjusted - employment' WHERE id=316;
UPDATE series SET title='Alabama, seasonally adjusted - unemployment' WHERE id=317;
UPDATE series SET title='Alabama, seasonally adjusted - employment' WHERE id=318;
UPDATE series SET title='Alabama, seasonally adjusted - labor force' WHERE id=319;
UPDATE series SET title='Alabama, seasonally adjusted - unemployment rate' WHERE id=320;
UPDATE series SET title='Rhode Island, seasonally adjusted - labor force' WHERE id=321;
UPDATE series SET title='Rhode Island, seasonally adjusted - employment' WHERE id=322;
UPDATE series SET title='Rhode Island, seasonally adjusted - unemployment' WHERE id=323;
UPDATE series SET title='Rhode Island, seasonally adjusted - unemployment rate' WHERE id=324;
UPDATE series SET title='Rhode Island, not seasonally adjusted - employment' WHERE id=325;
UPDATE series SET title='Rhode Island, not seasonally adjusted - unemployment' WHERE id=326;
UPDATE series SET title='Rhode Island, not seasonally adjusted - labor force' WHERE id=327;
UPDATE series SET title='Rhode Island, not seasonally adjusted - unemployment rate' WHERE id=328;
UPDATE series SET title='South Dakota, seasonally adjusted - employment' WHERE id=329;
UPDATE series SET title='South Dakota, seasonally adjusted - unemployment' WHERE id=330;
UPDATE series SET title='South Dakota, seasonally adjusted - labor force' WHERE id=331;
UPDATE series SET title='South Dakota, seasonally adjusted - unemployment rate' WHERE id=332;
UPDATE series SET title='South Dakota, not seasonally adjusted - labor force' WHERE id=333;
UPDATE series SET title='South Dakota, not seasonally adjusted - employment' WHERE id=334;
UPDATE series SET title='South Dakota, not seasonally adjusted - unemployment' WHERE id=335;
UPDATE series SET title='South Dakota, not seasonally adjusted - unemployment rate' WHERE id=336;
UPDATE series SET title='Georgia, not seasonally adjusted - employment' WHERE id=337;
UPDATE series SET title='Georgia, not seasonally adjusted - unemployment' WHERE id=338;
UPDATE series SET title='Georgia, not seasonally adjusted - labor force' WHERE id=339;
UPDATE series SET title='Georgia, not seasonally adjusted - unemployment rate' WHERE id=340;
UPDATE series SET title='Georgia, seasonally adjusted - unemployment rate' WHERE id=341;
UPDATE series SET title='Georgia, seasonally adjusted - labor force' WHERE id=342;
UPDATE series SET title='Georgia, seasonally adjusted - employment' WHERE id=343;
UPDATE series SET title='Georgia, seasonally adjusted - unemployment' WHERE id=344;
UPDATE series SET title='Colorado, not seasonally adjusted - employment' WHERE id=345;
UPDATE series SET title='Colorado, not seasonally adjusted - unemployment' WHERE id=346;
UPDATE series SET title='Colorado, not seasonally adjusted - labor force' WHERE id=347;
UPDATE series SET title='Colorado, not seasonally adjusted - unemployment rate' WHERE id=348;
UPDATE series SET title='Colorado, seasonally adjusted - labor force' WHERE id=349;
UPDATE series SET title='Colorado, seasonally adjusted - employment' WHERE id=350;
UPDATE series SET title='Colorado, seasonally adjusted - unemployment' WHERE id=351;
UPDATE series SET title='Colorado, seasonally adjusted - unemployment rate' WHERE id=352;
UPDATE series SET title='New Jersey, not seasonally adjusted - labor force' WHERE id=353;
UPDATE series SET title='New Jersey, not seasonally adjusted - unemployment rate' WHERE id=354;
UPDATE series SET title='New Jersey, seasonally adjusted - unemployment rate' WHERE id=355;
UPDATE series SET title='New Jersey, seasonally adjusted - unemployment' WHERE id=356;
UPDATE series SET title='New Jersey, seasonally adjusted - employment' WHERE id=357;
UPDATE series SET title='New Jersey, not seasonally adjusted - unemployment' WHERE id=358;
UPDATE series SET title='New Jersey, not seasonally adjusted - employment' WHERE id=359;
UPDATE series SET title='New Jersey, seasonally adjusted - labor force' WHERE id=360;
UPDATE series SET title='Washington, seasonally adjusted - labor force' WHERE id=361;
UPDATE series SET title='Washington, not seasonally adjusted - unemployment rate' WHERE id=362;
UPDATE series SET title='Washington, seasonally adjusted - unemployment' WHERE id=363;
UPDATE series SET title='Washington, seasonally adjusted - unemployment rate' WHERE id=364;
UPDATE series SET title='Washington, not seasonally adjusted - unemployment' WHERE id=365;
UPDATE series SET title='Washington, not seasonally adjusted - labor force' WHERE id=366;
UPDATE series SET title='Washington, seasonally adjusted - employment' WHERE id=367;
UPDATE series SET title='Washington, not seasonally adjusted - employment' WHERE id=368;
UPDATE series SET title='North Carolina, seasonally adjusted - unemployment rate' WHERE id=369;
UPDATE series SET title='North Carolina, seasonally adjusted - employment' WHERE id=370;
UPDATE series SET title='North Carolina, seasonally adjusted - unemployment' WHERE id=371;
UPDATE series SET title='North Carolina, seasonally adjusted - labor force' WHERE id=372;
UPDATE series SET title='North Carolina, not seasonally adjusted - labor force' WHERE id=373;
UPDATE series SET title='North Carolina, not seasonally adjusted - employment' WHERE id=374;
UPDATE series SET title='North Carolina, not seasonally adjusted - unemployment' WHERE id=375;
UPDATE series SET title='North Carolina, not seasonally adjusted - unemployment rate' WHERE id=376;
UPDATE series SET title='Tennessee, not seasonally adjusted - unemployment' WHERE id=377;
UPDATE series SET title='Tennessee, not seasonally adjusted - employment' WHERE id=378;
UPDATE series SET title='Tennessee, not seasonally adjusted - labor force' WHERE id=379;
UPDATE series SET title='Tennessee, not seasonally adjusted - unemployment rate' WHERE id=380;
UPDATE series SET title='Tennessee, seasonally adjusted - unemployment rate' WHERE id=381;
UPDATE series SET title='Tennessee, seasonally adjusted - labor force' WHERE id=382;
UPDATE series SET title='Tennessee, seasonally adjusted - unemployment' WHERE id=383;
UPDATE series SET title='Tennessee, seasonally adjusted - employment' WHERE id=384;
UPDATE series SET title='Texas, seasonally adjusted - unemployment rate' WHERE id=385;
UPDATE series SET title='Texas, seasonally adjusted - labor force' WHERE id=386;
UPDATE series SET title='Texas, seasonally adjusted - employment' WHERE id=387;
UPDATE series SET title='Texas, seasonally adjusted - unemployment' WHERE id=388;
UPDATE series SET title='Texas, not seasonally adjusted - unemployment rate' WHERE id=389;
UPDATE series SET title='Texas, not seasonally adjusted - employment' WHERE id=390;
UPDATE series SET title='Texas, not seasonally adjusted - unemployment' WHERE id=391;
UPDATE series SET title='Texas, not seasonally adjusted - labor force' WHERE id=392;
UPDATE series SET title='Nevada, seasonally adjusted - unemployment rate' WHERE id=393;
UPDATE series SET title='Nevada, seasonally adjusted - labor force' WHERE id=394;
UPDATE series SET title='Nevada, seasonally adjusted - unemployment' WHERE id=395;
UPDATE series SET title='Nevada, seasonally adjusted - employment' WHERE id=396;
UPDATE series SET title='Nevada, not seasonally adjusted - unemployment rate' WHERE id=397;
UPDATE series SET title='Nevada, not seasonally adjusted - unemployment' WHERE id=398;
UPDATE series SET title='Nevada, not seasonally adjusted - employment' WHERE id=399;
UPDATE series SET title='Nevada, not seasonally adjusted - labor force' WHERE id=400;
UPDATE series SET title='Maine, seasonally adjusted - unemployment' WHERE id=401;
UPDATE series SET title='Maine, not seasonally adjusted - unemployment rate' WHERE id=402;
UPDATE series SET title='Maine, seasonally adjusted - labor force' WHERE id=403;
UPDATE series SET title='Maine, not seasonally adjusted - labor force' WHERE id=404;
UPDATE series SET title='Maine, not seasonally adjusted - unemployment' WHERE id=405;
UPDATE series SET title='Maine, seasonally adjusted - unemployment rate' WHERE id=406;
UPDATE series SET title='Maine, not seasonally adjusted - employment' WHERE id=407;
UPDATE series SET title='Maine, seasonally adjusted - employment' WHERE id=408;
UPDATE series SET title='Mississippi, not seasonally adjusted - labor force' WHERE id=1;


-- UPDATE states_series dataset and slug according to re-mapping
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=2;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=3;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=5;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=6;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=8;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=9;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=11;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=12;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=13;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=15;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=16;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=18;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=19;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=21;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=22;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=23;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=25;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=26;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=28;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=29;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=30;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=32;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=33;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=35;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=36;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=38;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=39;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=41;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=42;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=43;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=45;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=46;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=48;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=49;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=50;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=52;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=53;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=55;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=56;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=58;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=59;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=60;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=62;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=63;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=65;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=66;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=67;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=69;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=70;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=72;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=73;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=75;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=76;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=77;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=79;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=80;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=82;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=83;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=84;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=86;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=87;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=89;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=90;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=92;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=93;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=94;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=96;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=97;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=99;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=100;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=102;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=103;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=104;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=106;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=107;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=109;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=110;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=112;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=113;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=115;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=116;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=118;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=119;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=120;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=122;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=123;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=125;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=126;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=127;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=129;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=130;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=133;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=135;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=136;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=138;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=139;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=140;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=142;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=143;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=145;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=146;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=148;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=149;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=150;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=152;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=153;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=155;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=156;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=158;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=159;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=161;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=162;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=163;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=165;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=166;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=168;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=169;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=171;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=172;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=174;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=175;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=176;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=178;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=179;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=181;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=182;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=184;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=185;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=187;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=188;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=190;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=191;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=193;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=194;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=195;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=197;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=198;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=200;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=201;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=203;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=204;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=205;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=207;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=208;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=210;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=211;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=213;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=214;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=215;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=217;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=218;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=220;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=221;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=222;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=224;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=226;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=227;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=228;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=230;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=231;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=233;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=234;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=236;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=237;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=239;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=240;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=241;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=243;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=244;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=246;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=247;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=249;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=250;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=252;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=253;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=254;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=256;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=257;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=258;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=260;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=261;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=264;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=265;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=267;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=269;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=270;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=271;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=273;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=274;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=276;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=277;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=278;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=280;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=281;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=283;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=284;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=286;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=287;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=288;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=290;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=291;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=293;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=294;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=295;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=297;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=298;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=300;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=301;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=303;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=304;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=306;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=307;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=309;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=310;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=312;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=313;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=314;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=316;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=317;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=319;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=320;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=322;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=323;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=325;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=326;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=327;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=329;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=330;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=332;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=333;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=335;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=336;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=337;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=339;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=340;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=342;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=343;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=345;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=346;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=348;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=349;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=350;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=352;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=353;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=355;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=356;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=358;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=359;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=361;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=362;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=364;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=365;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=367;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=368;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=369;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=371;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=372;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=374;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=375;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=377;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=378;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=380;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=381;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=383;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=384;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=385;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=387;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=388;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=390;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=391;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=393;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=395;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=397;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=398;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=399;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=4;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=7;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=10;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=14;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=17;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=20;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=27;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=31;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=34;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=37;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=40;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=44;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=47;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=51;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=54;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=57;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=61;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=64;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=68;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=71;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=74;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=78;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=81;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=85;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=88;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=91;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=95;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=98;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=101;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=108;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=111;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=114;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=117;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=121;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=124;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=128;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=131;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=132;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=134;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=137;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=141;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=144;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=147;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=151;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=154;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=157;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=160;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=164;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=167;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=170;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=177;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=180;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=183;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=186;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=189;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=192;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=196;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=199;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=202;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=206;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=209;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=212;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=216;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=219;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=223;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=225;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=229;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=232;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=235;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=238;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=242;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=245;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=251;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=255;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=259;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=262;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=263;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=266;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=268;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=272;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=275;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=279;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=282;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=285;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=289;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=292;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=296;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=302;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=308;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=311;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=315;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=318;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=321;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=324;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=328;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=331;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=334;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=338;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=341;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=344;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=347;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=351;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=354;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=357;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=360;
UPDATE states_series SET dataset='unemployment', slug='unemployment' WHERE id=363;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=366;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=370;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=376;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=379;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=382;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=386;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=389;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=392;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=394;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=396;
UPDATE states_series SET dataset='employment', slug='employment' WHERE id=400;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=1;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=24;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=105;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=173;
UPDATE states_series SET dataset='labor force', slug='labor-force' WHERE id=248;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=299;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=305;
UPDATE states_series SET dataset='unemployment rate', slug='unemployment-rate' WHERE id=373;


COMMIT;
